### PR TITLE
Add ssb-meme to plugins

### PR DESCRIPTION
**Pull request by Powersource**

### CODE REVIEW

**Comment by Powersource** [comment]
Reason it's conflicting is because I based this off of 4.0.1 to make it compatible with oasis right now.

**Comment by Powersource** [comment]
For reference

```
% du -h .ssb/flume/meme 
3.0M	.ssb/flume/meme
```

**Comment by Powersource** [comment]
Should be mergeable now

**Comment by christianbundy** [comment]
LGTM!

**Pull request merged**
